config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end

  mount Sidekiq::Web, at: "/sidekiq"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: "sessions" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  # spotify auth callback
  get '/auth/spotify/callback', to: 'users#spotify'
  get 'dashboard', to: 'dashboard#index'

  # help page
  get '/help', to: 'pages#help'

  resources :users, only: [:update, :destroy]

  get 'edit_account', to: 'users#edit', as: 'edit_user'

  # namespace :playlists do
  #   resources :spotify_restore, only: :update, as: :post
  # end

  resources :playlists, only: [:show, :destroy] do
    scope module: 'playlists' do
      resource :spotify_restore, only: :create
    end

    post 'initial_discover_weekly_sync', on: :collection

    collection do
      post 'sync_discover_weekly'
    end

  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ActionController::Base
  before_action :authenticate_user!
  
  layout "application"

  def index
    @playlists = current_user.playlists.order('id DESC')
  end
end

app/views/dashboard/index.html.erb
<% content_for :title do %>
  ReDiscover Weekly | Dashboard
<% end %>

<% if !current_user.has_discover_weekly? %>
    <div class="jumbotron">
      <h1 class="display-4">Welcome to <strong>Re</strong>Discover Weekly</h1>
      <p class="lead">Click the button below to back up this week's Discover Weekly playlist <strong>AND</strong> to turn on automatic backups for every week in the future.</p>
      <p><strong>Backup playlists will be pushed directly to your Spotify sidebar and stored here as well.</strong></p>
      <hr class="my-4">
      <p class="lead">
        <%= button_to "Start Backing Up Discover Weekly", initial_discover_weekly_sync_playlists_path, class: "btn btn-success btn-lg", role: "button", data: { disable_with: "Hold please..." } %>
      </p>
    </div>
<% end %>

<% if current_user.has_backups? %>
  <h2>Your Backups</h2>
  <table class="table table-striped backups-list-table">
    <tbody>
      <% @playlists.each do |pl| %>
      <tr>
        <td>
          Week of <%= pl.week_of.strftime(" %B %d, %Y") %></td>
        <td align="right">
          <div class="btn-group backups-list-table__buton-group" role="group">
            <%= link_to "View Tracks", playlist_path(pl), class: "btn btn-primary btn-sm" %>
            <%= link_to "Restore to Spotify", playlist_spotify_restore_path(pl), method: :post, class: "btn btn-info btn-sm", data: { disable_with: "Hold please..." } %>
            <%= link_to 'Delete', playlist_path(pl), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
          </div>
        </td>
      </tr>
      <% end -%>
    </tbody>
  </table>
<% end %>

<% if !current_user.has_backups? and current_user.has_discover_weekly? %>
  <div class="jumbotron">
    <p class="lead">It looks like we have your Discover Weekly playlist ID but you don't have any backups.</p>
    <hr class="my-4">
    <p class="lead">
      <%= button_to "Backup Now", sync_discover_weekly_playlists_path, class: "btn btn-success btn-lg", role: "button" %>
    </p>
  </div>
<% end %>